services:
  backend:
    build: 
      context: ./conduit-backend
      dockerfile: Dockerfile
    ports:
      - "8000"
    volumes:
      - backend-static:/app/staticfiles
      - backend-data:/app/conduit
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DEBUG=${DEBUG}
    networks:
      - conduit-network

  frontend:
    build:
      context: ./conduit-frontend
      dockerfile: Dockerfile
    ports:
      - "8282:8282"
    depends_on:
      - backend
    networks:
      - conduit-network

volumes:
  backend-static:
  backend-data:

networks:
  conduit-network:
           driver: bridge