services:
  backend:
    build: 
      context: ./conduit-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - backend-static:/app/staticfiles
      - backend-data:/app/conduit
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
  frontend:
    build:
      context: ./conduit-frontend
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - frontend-html:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  backend-static:
  backend-data:
  frontend-html: